name: 'Blank Issue'
description: 请使用 https://issue.zfile.vip 创建新的问题.
body:
  - type: markdown
    attributes:
      value: |
        **注意:**
        不要通过此页面创建问题, 请使用 https://issue.zfile.vip 创建新的问题.
        如果不是通过此链接创建的问题, 将会被直接关闭.
  - type: textarea
    id: add-a-description
    attributes:
      label: Add a description